# TPM plugins path
set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.config/tpm-plugins/'

# Settings
set -gq allow-passthrough on
set -g visual-activity off
set-option -g focus-events on

set -g base-index 1
setw -g pane-base-index 1

set -g mode-keys vi

# Bindings
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'r' send -X rectangle-toggle
bind-key -T copy-mode-vi 'y' send -X copy-pipe-and-cancel

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Plugins
set -g @tmux2k-theme 'gruvbox'
set -g @plugin '2kabhishek/tmux2k'
set -g @plugin 'tmux-plugins/tmux-yank'

# TPM setup
run '~/.config/tpm/tpm'
